[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jaxley-mech"
version = "0.1.0"  
description = ""
authors = [
]
requires-python = ">=3.8.0"
dependencies = [
    "jax[cpu]",
    "numpy",
    "pandas",
    "matplotlib",
    "networkx",
    "jaxley"
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "jupyter",
    "mkdocs",
    "mkdocs-material",
    "markdown-include",
    "mkdocs-redirects",
    "mkdocstrings[python]>=0.18",
    "neuron",
    "pytest",
    "pyright"
]

[tool.setuptools]
packages = {find = {}}
